/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.RTDE.impl;

public class VectorUchar extends java.util.AbstractList<Short> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorUchar(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorUchar obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ViconDataStreamSDKSwigJNI.delete_VectorUchar(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorUchar(short[] initialElements) {
    this();
    reserve(initialElements.length);

    for (short element : initialElements) {
      add(element);
    }
  }

  public VectorUchar(Iterable<Short> initialElements) {
    this();
    for (short element : initialElements) {
      add(element);
    }
  }

  public Short get(int index) {
    return doGet(index);
  }

  public Short set(int index, Short e) {
    return doSet(index, e);
  }

  public boolean add(Short e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Short e) {
    modCount++;
    doAdd(index, e);
  }

  public Short remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public VectorUchar() {
    this(ViconDataStreamSDKSwigJNI.new_VectorUchar__SWIG_0(), true);
  }

  public VectorUchar(VectorUchar other) {
    this(ViconDataStreamSDKSwigJNI.new_VectorUchar__SWIG_1(VectorUchar.getCPtr(other), other), true);
  }

  public long capacity() {
    return ViconDataStreamSDKSwigJNI.VectorUchar_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    ViconDataStreamSDKSwigJNI.VectorUchar_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return ViconDataStreamSDKSwigJNI.VectorUchar_isEmpty(swigCPtr, this);
  }

  public void clear() {
    ViconDataStreamSDKSwigJNI.VectorUchar_clear(swigCPtr, this);
  }

  public VectorUchar(int count, short value) {
    this(ViconDataStreamSDKSwigJNI.new_VectorUchar__SWIG_2(count, value), true);
  }

  private int doSize() {
    return ViconDataStreamSDKSwigJNI.VectorUchar_doSize(swigCPtr, this);
  }

  private void doAdd(short x) {
    ViconDataStreamSDKSwigJNI.VectorUchar_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, short x) {
    ViconDataStreamSDKSwigJNI.VectorUchar_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private short doRemove(int index) {
    return ViconDataStreamSDKSwigJNI.VectorUchar_doRemove(swigCPtr, this, index);
  }

  private short doGet(int index) {
    return ViconDataStreamSDKSwigJNI.VectorUchar_doGet(swigCPtr, this, index);
  }

  private short doSet(int index, short val) {
    return ViconDataStreamSDKSwigJNI.VectorUchar_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    ViconDataStreamSDKSwigJNI.VectorUchar_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
