/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.RTDE.impl;

public class PolyScopeVersion {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PolyScopeVersion(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PolyScopeVersion obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RTDE_MODULEJNI.delete_PolyScopeVersion(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PolyScopeVersion(String str) {
    this(RTDE_MODULEJNI.new_PolyScopeVersion(str), true);
  }

  public void setMajor(int value) {
    RTDE_MODULEJNI.PolyScopeVersion_major_set(swigCPtr, this, value);
  }

  public int getMajor() {
    return RTDE_MODULEJNI.PolyScopeVersion_major_get(swigCPtr, this);
  }

  public void setMinor(int value) {
    RTDE_MODULEJNI.PolyScopeVersion_minor_set(swigCPtr, this, value);
  }

  public int getMinor() {
    return RTDE_MODULEJNI.PolyScopeVersion_minor_get(swigCPtr, this);
  }

  public void setPatch(int value) {
    RTDE_MODULEJNI.PolyScopeVersion_patch_set(swigCPtr, this, value);
  }

  public int getPatch() {
    return RTDE_MODULEJNI.PolyScopeVersion_patch_get(swigCPtr, this);
  }

  public void setBuild(int value) {
    RTDE_MODULEJNI.PolyScopeVersion_build_set(swigCPtr, this, value);
  }

  public int getBuild() {
    return RTDE_MODULEJNI.PolyScopeVersion_build_get(swigCPtr, this);
  }

  public String toString() {
    return RTDE_MODULEJNI.PolyScopeVersion_toString(swigCPtr, this);
  }

  public void parse(String str) {
    RTDE_MODULEJNI.PolyScopeVersion_parse(swigCPtr, this, str);
  }

}
