/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.RTDE.impl;

public final class ProgramState {
  public final static ProgramState STOPPED = new ProgramState("STOPPED");
  public final static ProgramState PLAYING = new ProgramState("PLAYING");
  public final static ProgramState PAUSED = new ProgramState("PAUSED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ProgramState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ProgramState.class + " with value " + swigValue);
  }

  private ProgramState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ProgramState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ProgramState(String swigName, ProgramState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ProgramState[] swigValues = { STOPPED, PLAYING, PAUSED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

