/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.RTDE.impl;

public class RobotState {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RobotState(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RobotState obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RTDE_MODULEJNI.delete_RobotState(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RobotState() {
    this(RTDE_MODULEJNI.new_RobotState(), true);
  }

  public boolean lockUpdateStateMutex() {
    return RTDE_MODULEJNI.RobotState_lockUpdateStateMutex(swigCPtr, this);
  }

  public boolean unlockUpdateStateMutex() {
    return RTDE_MODULEJNI.RobotState_unlockUpdateStateMutex(swigCPtr, this);
  }

  public double getTimestamp() {
    return RTDE_MODULEJNI.RobotState_getTimestamp(swigCPtr, this);
  }

  public void setTimestamp(double timestamp) {
    RTDE_MODULEJNI.RobotState_setTimestamp(swigCPtr, this, timestamp);
  }

  public VectorDouble getTarget_q() {
    return new VectorDouble(RTDE_MODULEJNI.RobotState_getTarget_q(swigCPtr, this), false);
  }

  public void setTarget_q(VectorDouble target_q) {
    RTDE_MODULEJNI.RobotState_setTarget_q(swigCPtr, this, VectorDouble.getCPtr(target_q), target_q);
  }

  public VectorDouble getTarget_qd() {
    return new VectorDouble(RTDE_MODULEJNI.RobotState_getTarget_qd(swigCPtr, this), false);
  }

  public void setTarget_qd(VectorDouble target_qd) {
    RTDE_MODULEJNI.RobotState_setTarget_qd(swigCPtr, this, VectorDouble.getCPtr(target_qd), target_qd);
  }

  public VectorDouble getTarget_qdd() {
    return new VectorDouble(RTDE_MODULEJNI.RobotState_getTarget_qdd(swigCPtr, this), false);
  }

  public void setTarget_qdd(VectorDouble target_qdd) {
    RTDE_MODULEJNI.RobotState_setTarget_qdd(swigCPtr, this, VectorDouble.getCPtr(target_qdd), target_qdd);
  }

  public VectorDouble getTarget_current() {
    return new VectorDouble(RTDE_MODULEJNI.RobotState_getTarget_current(swigCPtr, this), false);
  }

  public void setTarget_current(VectorDouble target_current) {
    RTDE_MODULEJNI.RobotState_setTarget_current(swigCPtr, this, VectorDouble.getCPtr(target_current), target_current);
  }

  public VectorDouble getTarget_moment() {
    return new VectorDouble(RTDE_MODULEJNI.RobotState_getTarget_moment(swigCPtr, this), false);
  }

  public void setTarget_moment(VectorDouble target_moment) {
    RTDE_MODULEJNI.RobotState_setTarget_moment(swigCPtr, this, VectorDouble.getCPtr(target_moment), target_moment);
  }

  public VectorDouble getActual_q() {
    return new VectorDouble(RTDE_MODULEJNI.RobotState_getActual_q(swigCPtr, this), false);
  }

  public void setActual_q(VectorDouble actual_q) {
    RTDE_MODULEJNI.RobotState_setActual_q(swigCPtr, this, VectorDouble.getCPtr(actual_q), actual_q);
  }

  public VectorDouble getActual_qd() {
    return new VectorDouble(RTDE_MODULEJNI.RobotState_getActual_qd(swigCPtr, this), false);
  }

  public void setActual_qd(VectorDouble actual_qd) {
    RTDE_MODULEJNI.RobotState_setActual_qd(swigCPtr, this, VectorDouble.getCPtr(actual_qd), actual_qd);
  }

  public VectorDouble getActual_current() {
    return new VectorDouble(RTDE_MODULEJNI.RobotState_getActual_current(swigCPtr, this), false);
  }

  public void setActual_current(VectorDouble actual_current) {
    RTDE_MODULEJNI.RobotState_setActual_current(swigCPtr, this, VectorDouble.getCPtr(actual_current), actual_current);
  }

  public VectorDouble getJoint_control_output() {
    return new VectorDouble(RTDE_MODULEJNI.RobotState_getJoint_control_output(swigCPtr, this), false);
  }

  public void setJoint_control_output(VectorDouble joint_control_output) {
    RTDE_MODULEJNI.RobotState_setJoint_control_output(swigCPtr, this, VectorDouble.getCPtr(joint_control_output), joint_control_output);
  }

  public VectorDouble getActual_TCP_pose() {
    return new VectorDouble(RTDE_MODULEJNI.RobotState_getActual_TCP_pose(swigCPtr, this), false);
  }

  public void setActual_TCP_pose(VectorDouble actual_TCP_pose) {
    RTDE_MODULEJNI.RobotState_setActual_TCP_pose(swigCPtr, this, VectorDouble.getCPtr(actual_TCP_pose), actual_TCP_pose);
  }

  public VectorDouble getActual_TCP_speed() {
    return new VectorDouble(RTDE_MODULEJNI.RobotState_getActual_TCP_speed(swigCPtr, this), false);
  }

  public void setActual_TCP_speed(VectorDouble actual_TCP_speed) {
    RTDE_MODULEJNI.RobotState_setActual_TCP_speed(swigCPtr, this, VectorDouble.getCPtr(actual_TCP_speed), actual_TCP_speed);
  }

  public VectorDouble getActual_TCP_force() {
    return new VectorDouble(RTDE_MODULEJNI.RobotState_getActual_TCP_force(swigCPtr, this), false);
  }

  public void setActual_TCP_force(VectorDouble actual_TCP_force) {
    RTDE_MODULEJNI.RobotState_setActual_TCP_force(swigCPtr, this, VectorDouble.getCPtr(actual_TCP_force), actual_TCP_force);
  }

  public VectorDouble getTarget_TCP_pose() {
    return new VectorDouble(RTDE_MODULEJNI.RobotState_getTarget_TCP_pose(swigCPtr, this), false);
  }

  public void setTarget_TCP_pose(VectorDouble target_TCP_pose) {
    RTDE_MODULEJNI.RobotState_setTarget_TCP_pose(swigCPtr, this, VectorDouble.getCPtr(target_TCP_pose), target_TCP_pose);
  }

  public VectorDouble getTarget_TCP_speed() {
    return new VectorDouble(RTDE_MODULEJNI.RobotState_getTarget_TCP_speed(swigCPtr, this), false);
  }

  public void setTarget_TCP_speed(VectorDouble target_TCP_speed) {
    RTDE_MODULEJNI.RobotState_setTarget_TCP_speed(swigCPtr, this, VectorDouble.getCPtr(target_TCP_speed), target_TCP_speed);
  }

  public java.math.BigInteger getActual_digital_input_bits() {
    return RTDE_MODULEJNI.RobotState_getActual_digital_input_bits(swigCPtr, this);
  }

  public void setActual_digital_input_bits(java.math.BigInteger actual_digital_input_bits) {
    RTDE_MODULEJNI.RobotState_setActual_digital_input_bits(swigCPtr, this, actual_digital_input_bits);
  }

  public VectorDouble getJoint_temperatures() {
    return new VectorDouble(RTDE_MODULEJNI.RobotState_getJoint_temperatures(swigCPtr, this), false);
  }

  public void setJoint_temperatures(VectorDouble joint_temperatures) {
    RTDE_MODULEJNI.RobotState_setJoint_temperatures(swigCPtr, this, VectorDouble.getCPtr(joint_temperatures), joint_temperatures);
  }

  public double getActual_execution_time() {
    return RTDE_MODULEJNI.RobotState_getActual_execution_time(swigCPtr, this);
  }

  public void setActual_execution_time(double actual_execution_time) {
    RTDE_MODULEJNI.RobotState_setActual_execution_time(swigCPtr, this, actual_execution_time);
  }

  public int getRobot_mode() {
    return RTDE_MODULEJNI.RobotState_getRobot_mode(swigCPtr, this);
  }

  public void setRobot_mode(int robot_mode) {
    RTDE_MODULEJNI.RobotState_setRobot_mode(swigCPtr, this, robot_mode);
  }

  public long getRobot_status() {
    return RTDE_MODULEJNI.RobotState_getRobot_status(swigCPtr, this);
  }

  public void setRobot_status(long robot_status) {
    RTDE_MODULEJNI.RobotState_setRobot_status(swigCPtr, this, robot_status);
  }

  public long getSafety_status_bits() {
    return RTDE_MODULEJNI.RobotState_getSafety_status_bits(swigCPtr, this);
  }

  public void setSafety_status_bits(long safety_status_bits) {
    RTDE_MODULEJNI.RobotState_setSafety_status_bits(swigCPtr, this, safety_status_bits);
  }

  public VectorInt getJoint_mode() {
    return new VectorInt(RTDE_MODULEJNI.RobotState_getJoint_mode(swigCPtr, this), false);
  }

  public void setJoint_mode(VectorInt joint_mode) {
    RTDE_MODULEJNI.RobotState_setJoint_mode(swigCPtr, this, VectorInt.getCPtr(joint_mode), joint_mode);
  }

  public int getSafety_mode() {
    return RTDE_MODULEJNI.RobotState_getSafety_mode(swigCPtr, this);
  }

  public void setSafety_mode(int safety_mode) {
    RTDE_MODULEJNI.RobotState_setSafety_mode(swigCPtr, this, safety_mode);
  }

  public VectorDouble getActual_tool_accelerometer() {
    return new VectorDouble(RTDE_MODULEJNI.RobotState_getActual_tool_accelerometer(swigCPtr, this), false);
  }

  public void setActual_tool_accelerometer(VectorDouble actual_tool_accelerometer) {
    RTDE_MODULEJNI.RobotState_setActual_tool_accelerometer(swigCPtr, this, VectorDouble.getCPtr(actual_tool_accelerometer), actual_tool_accelerometer);
  }

  public double getSpeed_scaling() {
    return RTDE_MODULEJNI.RobotState_getSpeed_scaling(swigCPtr, this);
  }

  public void setSpeed_scaling(double speed_scaling) {
    RTDE_MODULEJNI.RobotState_setSpeed_scaling(swigCPtr, this, speed_scaling);
  }

  public double getTarget_speed_fraction() {
    return RTDE_MODULEJNI.RobotState_getTarget_speed_fraction(swigCPtr, this);
  }

  public void setTarget_speed_fraction(double target_speed_fraction) {
    RTDE_MODULEJNI.RobotState_setTarget_speed_fraction(swigCPtr, this, target_speed_fraction);
  }

  public double getActual_momentum() {
    return RTDE_MODULEJNI.RobotState_getActual_momentum(swigCPtr, this);
  }

  public void setActual_momentum(double actual_momentum) {
    RTDE_MODULEJNI.RobotState_setActual_momentum(swigCPtr, this, actual_momentum);
  }

  public double getActual_main_voltage() {
    return RTDE_MODULEJNI.RobotState_getActual_main_voltage(swigCPtr, this);
  }

  public void setActual_main_voltage(double actual_main_voltage) {
    RTDE_MODULEJNI.RobotState_setActual_main_voltage(swigCPtr, this, actual_main_voltage);
  }

  public double getActual_robot_voltage() {
    return RTDE_MODULEJNI.RobotState_getActual_robot_voltage(swigCPtr, this);
  }

  public void setActual_robot_voltage(double actual_robot_voltage) {
    RTDE_MODULEJNI.RobotState_setActual_robot_voltage(swigCPtr, this, actual_robot_voltage);
  }

  public double getActual_robot_current() {
    return RTDE_MODULEJNI.RobotState_getActual_robot_current(swigCPtr, this);
  }

  public void setActual_robot_current(double actual_robot_current) {
    RTDE_MODULEJNI.RobotState_setActual_robot_current(swigCPtr, this, actual_robot_current);
  }

  public VectorDouble getActual_joint_voltage() {
    return new VectorDouble(RTDE_MODULEJNI.RobotState_getActual_joint_voltage(swigCPtr, this), false);
  }

  public void setActual_joint_voltage(VectorDouble actual_joint_voltage) {
    RTDE_MODULEJNI.RobotState_setActual_joint_voltage(swigCPtr, this, VectorDouble.getCPtr(actual_joint_voltage), actual_joint_voltage);
  }

  public java.math.BigInteger getActual_digital_output_bits() {
    return RTDE_MODULEJNI.RobotState_getActual_digital_output_bits(swigCPtr, this);
  }

  public void setActual_digital_output_bits(java.math.BigInteger actual_digital_output_bits) {
    RTDE_MODULEJNI.RobotState_setActual_digital_output_bits(swigCPtr, this, actual_digital_output_bits);
  }

  public long getRuntime_state() {
    return RTDE_MODULEJNI.RobotState_getRuntime_state(swigCPtr, this);
  }

  public double getStandard_analog_input_0() {
    return RTDE_MODULEJNI.RobotState_getStandard_analog_input_0(swigCPtr, this);
  }

  public void setStandard_analog_input_0(double standard_analog_input_0) {
    RTDE_MODULEJNI.RobotState_setStandard_analog_input_0(swigCPtr, this, standard_analog_input_0);
  }

  public double getStandard_analog_input_1() {
    return RTDE_MODULEJNI.RobotState_getStandard_analog_input_1(swigCPtr, this);
  }

  public void setStandard_analog_input_1(double standard_analog_input_1) {
    RTDE_MODULEJNI.RobotState_setStandard_analog_input_1(swigCPtr, this, standard_analog_input_1);
  }

  public double getStandard_analog_output_0() {
    return RTDE_MODULEJNI.RobotState_getStandard_analog_output_0(swigCPtr, this);
  }

  public void setStandard_analog_output_0(double standard_analog_output_0) {
    RTDE_MODULEJNI.RobotState_setStandard_analog_output_0(swigCPtr, this, standard_analog_output_0);
  }

  public double getStandard_analog_output_1() {
    return RTDE_MODULEJNI.RobotState_getStandard_analog_output_1(swigCPtr, this);
  }

  public void setStandard_analog_output_1(double standard_analog_output_1) {
    RTDE_MODULEJNI.RobotState_setStandard_analog_output_1(swigCPtr, this, standard_analog_output_1);
  }

  public void setRuntime_state(long runtime_state) {
    RTDE_MODULEJNI.RobotState_setRuntime_state(swigCPtr, this, runtime_state);
  }

  public long getOutput_bit_registers0_to_31() {
    return RTDE_MODULEJNI.RobotState_getOutput_bit_registers0_to_31(swigCPtr, this);
  }

  public void setOutput_bit_registers0_to_31(long output_bit_registers0_to_31) {
    RTDE_MODULEJNI.RobotState_setOutput_bit_registers0_to_31(swigCPtr, this, output_bit_registers0_to_31);
  }

  public long getOutput_bit_registers32_to_63() {
    return RTDE_MODULEJNI.RobotState_getOutput_bit_registers32_to_63(swigCPtr, this);
  }

  public void setOutput_bit_registers32_to_63(long output_bit_registers32_to_63) {
    RTDE_MODULEJNI.RobotState_setOutput_bit_registers32_to_63(swigCPtr, this, output_bit_registers32_to_63);
  }

  public int getOutput_int_register_0() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_0(swigCPtr, this);
  }

  public void setOutput_int_register_0(int output_int_register_0) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_0(swigCPtr, this, output_int_register_0);
  }

  public int getOutput_int_register_1() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_1(swigCPtr, this);
  }

  public void setOutput_int_register_1(int output_int_register_1) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_1(swigCPtr, this, output_int_register_1);
  }

  public int getOutput_int_register_2() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_2(swigCPtr, this);
  }

  public void setOutput_int_register_2(int output_int_register_2) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_2(swigCPtr, this, output_int_register_2);
  }

  public int getOutput_int_register_3() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_3(swigCPtr, this);
  }

  public void setOutput_int_register_3(int output_int_register_3) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_3(swigCPtr, this, output_int_register_3);
  }

  public int getOutput_int_register_4() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_4(swigCPtr, this);
  }

  public void setOutput_int_register_4(int output_int_register_4) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_4(swigCPtr, this, output_int_register_4);
  }

  public int getOutput_int_register_5() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_5(swigCPtr, this);
  }

  public void setOutput_int_register_5(int output_int_register_5) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_5(swigCPtr, this, output_int_register_5);
  }

  public int getOutput_int_register_6() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_6(swigCPtr, this);
  }

  public void setOutput_int_register_6(int output_int_register_6) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_6(swigCPtr, this, output_int_register_6);
  }

  public int getOutput_int_register_7() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_7(swigCPtr, this);
  }

  public void setOutput_int_register_7(int output_int_register_7) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_7(swigCPtr, this, output_int_register_7);
  }

  public int getOutput_int_register_8() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_8(swigCPtr, this);
  }

  public void setOutput_int_register_8(int output_int_register_8) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_8(swigCPtr, this, output_int_register_8);
  }

  public int getOutput_int_register_9() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_9(swigCPtr, this);
  }

  public void setOutput_int_register_9(int output_int_register_9) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_9(swigCPtr, this, output_int_register_9);
  }

  public int getOutput_int_register_10() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_10(swigCPtr, this);
  }

  public void setOutput_int_register_10(int output_int_register_10) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_10(swigCPtr, this, output_int_register_10);
  }

  public int getOutput_int_register_11() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_11(swigCPtr, this);
  }

  public void setOutput_int_register_11(int output_int_register_11) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_11(swigCPtr, this, output_int_register_11);
  }

  public int getOutput_int_register_12() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_12(swigCPtr, this);
  }

  public void setOutput_int_register_12(int output_int_register_12) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_12(swigCPtr, this, output_int_register_12);
  }

  public int getOutput_int_register_13() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_13(swigCPtr, this);
  }

  public void setOutput_int_register_13(int output_int_register_13) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_13(swigCPtr, this, output_int_register_13);
  }

  public int getOutput_int_register_14() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_14(swigCPtr, this);
  }

  public void setOutput_int_register_14(int output_int_register_14) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_14(swigCPtr, this, output_int_register_14);
  }

  public int getOutput_int_register_15() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_15(swigCPtr, this);
  }

  public void setOutput_int_register_15(int output_int_register_15) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_15(swigCPtr, this, output_int_register_15);
  }

  public int getOutput_int_register_16() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_16(swigCPtr, this);
  }

  public void setOutput_int_register_16(int output_int_register_16) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_16(swigCPtr, this, output_int_register_16);
  }

  public int getOutput_int_register_17() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_17(swigCPtr, this);
  }

  public void setOutput_int_register_17(int output_int_register_17) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_17(swigCPtr, this, output_int_register_17);
  }

  public int getOutput_int_register_18() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_18(swigCPtr, this);
  }

  public void setOutput_int_register_18(int output_int_register_18) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_18(swigCPtr, this, output_int_register_18);
  }

  public int getOutput_int_register_19() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_19(swigCPtr, this);
  }

  public void setOutput_int_register_19(int output_int_register_19) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_19(swigCPtr, this, output_int_register_19);
  }

  public int getOutput_int_register_20() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_20(swigCPtr, this);
  }

  public void setOutput_int_register_20(int output_int_register_20) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_20(swigCPtr, this, output_int_register_20);
  }

  public int getOutput_int_register_21() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_21(swigCPtr, this);
  }

  public void setOutput_int_register_21(int output_int_register_21) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_21(swigCPtr, this, output_int_register_21);
  }

  public int getOutput_int_register_22() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_22(swigCPtr, this);
  }

  public void setOutput_int_register_22(int output_int_register_22) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_22(swigCPtr, this, output_int_register_22);
  }

  public int getOutput_int_register_23() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_23(swigCPtr, this);
  }

  public void setOutput_int_register_23(int output_int_register_23) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_23(swigCPtr, this, output_int_register_23);
  }

  public int getOutput_int_register_24() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_24(swigCPtr, this);
  }

  public void setOutput_int_register_24(int output_int_register_24) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_24(swigCPtr, this, output_int_register_24);
  }

  public int getOutput_int_register_25() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_25(swigCPtr, this);
  }

  public void setOutput_int_register_25(int output_int_register_25) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_25(swigCPtr, this, output_int_register_25);
  }

  public int getOutput_int_register_26() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_26(swigCPtr, this);
  }

  public void setOutput_int_register_26(int output_int_register_26) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_26(swigCPtr, this, output_int_register_26);
  }

  public int getOutput_int_register_27() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_27(swigCPtr, this);
  }

  public void setOutput_int_register_27(int output_int_register_27) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_27(swigCPtr, this, output_int_register_27);
  }

  public int getOutput_int_register_28() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_28(swigCPtr, this);
  }

  public void setOutput_int_register_28(int output_int_register_28) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_28(swigCPtr, this, output_int_register_28);
  }

  public int getOutput_int_register_29() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_29(swigCPtr, this);
  }

  public void setOutput_int_register_29(int output_int_register_29) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_29(swigCPtr, this, output_int_register_29);
  }

  public int getOutput_int_register_30() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_30(swigCPtr, this);
  }

  public void setOutput_int_register_30(int output_int_register_30) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_30(swigCPtr, this, output_int_register_30);
  }

  public int getOutput_int_register_31() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_31(swigCPtr, this);
  }

  public void setOutput_int_register_31(int output_int_register_31) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_31(swigCPtr, this, output_int_register_31);
  }

  public int getOutput_int_register_32() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_32(swigCPtr, this);
  }

  public void setOutput_int_register_32(int output_int_register_32) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_32(swigCPtr, this, output_int_register_32);
  }

  public int getOutput_int_register_33() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_33(swigCPtr, this);
  }

  public void setOutput_int_register_33(int output_int_register_33) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_33(swigCPtr, this, output_int_register_33);
  }

  public int getOutput_int_register_34() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_34(swigCPtr, this);
  }

  public void setOutput_int_register_34(int output_int_register_24) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_34(swigCPtr, this, output_int_register_24);
  }

  public int getOutput_int_register_35() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_35(swigCPtr, this);
  }

  public void setOutput_int_register_35(int output_int_register_35) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_35(swigCPtr, this, output_int_register_35);
  }

  public int getOutput_int_register_36() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_36(swigCPtr, this);
  }

  public void setOutput_int_register_36(int output_int_register_36) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_36(swigCPtr, this, output_int_register_36);
  }

  public int getOutput_int_register_37() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_37(swigCPtr, this);
  }

  public void setOutput_int_register_37(int output_int_register_37) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_37(swigCPtr, this, output_int_register_37);
  }

  public int getOutput_int_register_38() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_38(swigCPtr, this);
  }

  public void setOutput_int_register_38(int output_int_register_38) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_38(swigCPtr, this, output_int_register_38);
  }

  public int getOutput_int_register_39() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_39(swigCPtr, this);
  }

  public void setOutput_int_register_39(int output_int_register_39) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_39(swigCPtr, this, output_int_register_39);
  }

  public int getOutput_int_register_40() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_40(swigCPtr, this);
  }

  public void setOutput_int_register_40(int output_int_register_40) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_40(swigCPtr, this, output_int_register_40);
  }

  public int getOutput_int_register_41() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_41(swigCPtr, this);
  }

  public void setOutput_int_register_41(int output_int_register_41) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_41(swigCPtr, this, output_int_register_41);
  }

  public int getOutput_int_register_42() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_42(swigCPtr, this);
  }

  public void setOutput_int_register_42(int output_int_register_42) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_42(swigCPtr, this, output_int_register_42);
  }

  public int getOutput_int_register_43() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_43(swigCPtr, this);
  }

  public void setOutput_int_register_43(int output_int_register_43) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_43(swigCPtr, this, output_int_register_43);
  }

  public int getOutput_int_register_44() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_44(swigCPtr, this);
  }

  public void setOutput_int_register_44(int output_int_register_44) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_44(swigCPtr, this, output_int_register_44);
  }

  public int getOutput_int_register_45() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_45(swigCPtr, this);
  }

  public void setOutput_int_register_45(int output_int_register_45) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_45(swigCPtr, this, output_int_register_45);
  }

  public int getOutput_int_register_46() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_46(swigCPtr, this);
  }

  public void setOutput_int_register_46(int output_int_register_46) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_46(swigCPtr, this, output_int_register_46);
  }

  public int getOutput_int_register_47() {
    return RTDE_MODULEJNI.RobotState_getOutput_int_register_47(swigCPtr, this);
  }

  public void setOutput_int_register_47(int output_int_register_47) {
    RTDE_MODULEJNI.RobotState_setOutput_int_register_47(swigCPtr, this, output_int_register_47);
  }

  public double getOutput_double_register_0() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_0(swigCPtr, this);
  }

  public void setOutput_double_register_0(double output_double_register_0) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_0(swigCPtr, this, output_double_register_0);
  }

  public double getOutput_double_register_1() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_1(swigCPtr, this);
  }

  public void setOutput_double_register_1(double output_double_register_1) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_1(swigCPtr, this, output_double_register_1);
  }

  public double getOutput_double_register_2() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_2(swigCPtr, this);
  }

  public void setOutput_double_register_2(double output_double_register_2) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_2(swigCPtr, this, output_double_register_2);
  }

  public double getOutput_double_register_3() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_3(swigCPtr, this);
  }

  public void setOutput_double_register_3(double output_double_register_3) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_3(swigCPtr, this, output_double_register_3);
  }

  public double getOutput_double_register_4() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_4(swigCPtr, this);
  }

  public void setOutput_double_register_4(double output_double_register_4) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_4(swigCPtr, this, output_double_register_4);
  }

  public double getOutput_double_register_5() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_5(swigCPtr, this);
  }

  public void setOutput_double_register_5(double output_double_register_5) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_5(swigCPtr, this, output_double_register_5);
  }

  public double getOutput_double_register_6() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_6(swigCPtr, this);
  }

  public void setOutput_double_register_6(double output_double_register_6) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_6(swigCPtr, this, output_double_register_6);
  }

  public double getOutput_double_register_7() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_7(swigCPtr, this);
  }

  public void setOutput_double_register_7(double output_double_register_7) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_7(swigCPtr, this, output_double_register_7);
  }

  public double getOutput_double_register_8() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_8(swigCPtr, this);
  }

  public void setOutput_double_register_8(double output_double_register_8) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_8(swigCPtr, this, output_double_register_8);
  }

  public double getOutput_double_register_9() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_9(swigCPtr, this);
  }

  public void setOutput_double_register_9(double output_double_register_9) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_9(swigCPtr, this, output_double_register_9);
  }

  public double getOutput_double_register_10() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_10(swigCPtr, this);
  }

  public void setOutput_double_register_10(double output_double_register_10) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_10(swigCPtr, this, output_double_register_10);
  }

  public double getOutput_double_register_11() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_11(swigCPtr, this);
  }

  public void setOutput_double_register_11(double output_double_register_11) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_11(swigCPtr, this, output_double_register_11);
  }

  public double getOutput_double_register_12() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_12(swigCPtr, this);
  }

  public void setOutput_double_register_12(double output_double_register_12) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_12(swigCPtr, this, output_double_register_12);
  }

  public double getOutput_double_register_13() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_13(swigCPtr, this);
  }

  public void setOutput_double_register_13(double output_double_register_13) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_13(swigCPtr, this, output_double_register_13);
  }

  public double getOutput_double_register_14() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_14(swigCPtr, this);
  }

  public void setOutput_double_register_14(double output_double_register_14) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_14(swigCPtr, this, output_double_register_14);
  }

  public double getOutput_double_register_15() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_15(swigCPtr, this);
  }

  public void setOutput_double_register_15(double output_double_register_15) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_15(swigCPtr, this, output_double_register_15);
  }

  public double getOutput_double_register_16() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_16(swigCPtr, this);
  }

  public void setOutput_double_register_16(double output_double_register_16) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_16(swigCPtr, this, output_double_register_16);
  }

  public double getOutput_double_register_17() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_17(swigCPtr, this);
  }

  public void setOutput_double_register_17(double output_double_register_17) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_17(swigCPtr, this, output_double_register_17);
  }

  public double getOutput_double_register_18() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_18(swigCPtr, this);
  }

  public void setOutput_double_register_18(double output_double_register_18) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_18(swigCPtr, this, output_double_register_18);
  }

  public double getOutput_double_register_19() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_19(swigCPtr, this);
  }

  public void setOutput_double_register_19(double output_double_register_19) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_19(swigCPtr, this, output_double_register_19);
  }

  public double getOutput_double_register_20() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_20(swigCPtr, this);
  }

  public void setOutput_double_register_20(double output_double_register_20) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_20(swigCPtr, this, output_double_register_20);
  }

  public double getOutput_double_register_21() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_21(swigCPtr, this);
  }

  public void setOutput_double_register_21(double output_double_register_21) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_21(swigCPtr, this, output_double_register_21);
  }

  public double getOutput_double_register_22() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_22(swigCPtr, this);
  }

  public void setOutput_double_register_22(double output_double_register_22) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_22(swigCPtr, this, output_double_register_22);
  }

  public double getOutput_double_register_23() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_23(swigCPtr, this);
  }

  public void setOutput_double_register_23(double output_double_register_23) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_23(swigCPtr, this, output_double_register_23);
  }

  public double getOutput_double_register_24() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_24(swigCPtr, this);
  }

  public void setOutput_double_register_24(double output_double_register_24) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_24(swigCPtr, this, output_double_register_24);
  }

  public double getOutput_double_register_25() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_25(swigCPtr, this);
  }

  public void setOutput_double_register_25(double output_double_register_25) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_25(swigCPtr, this, output_double_register_25);
  }

  public double getOutput_double_register_26() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_26(swigCPtr, this);
  }

  public void setOutput_double_register_26(double output_double_register_26) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_26(swigCPtr, this, output_double_register_26);
  }

  public double getOutput_double_register_27() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_27(swigCPtr, this);
  }

  public void setOutput_double_register_27(double output_double_register_27) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_27(swigCPtr, this, output_double_register_27);
  }

  public double getOutput_double_register_28() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_28(swigCPtr, this);
  }

  public void setOutput_double_register_28(double output_double_register_28) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_28(swigCPtr, this, output_double_register_28);
  }

  public double getOutput_double_register_29() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_29(swigCPtr, this);
  }

  public void setOutput_double_register_29(double output_double_register_29) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_29(swigCPtr, this, output_double_register_29);
  }

  public double getOutput_double_register_30() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_30(swigCPtr, this);
  }

  public void setOutput_double_register_30(double output_double_register_30) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_30(swigCPtr, this, output_double_register_30);
  }

  public double getOutput_double_register_31() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_31(swigCPtr, this);
  }

  public void setOutput_double_register_31(double output_double_register_31) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_31(swigCPtr, this, output_double_register_31);
  }

  public double getOutput_double_register_32() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_32(swigCPtr, this);
  }

  public void setOutput_double_register_32(double output_double_register_32) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_32(swigCPtr, this, output_double_register_32);
  }

  public double getOutput_double_register_33() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_33(swigCPtr, this);
  }

  public void setOutput_double_register_33(double output_double_register_33) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_33(swigCPtr, this, output_double_register_33);
  }

  public double getOutput_double_register_34() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_34(swigCPtr, this);
  }

  public void setOutput_double_register_34(double output_double_register_34) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_34(swigCPtr, this, output_double_register_34);
  }

  public double getOutput_double_register_35() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_35(swigCPtr, this);
  }

  public void setOutput_double_register_35(double output_double_register_35) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_35(swigCPtr, this, output_double_register_35);
  }

  public double getOutput_double_register_36() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_36(swigCPtr, this);
  }

  public void setOutput_double_register_36(double output_double_register_36) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_36(swigCPtr, this, output_double_register_36);
  }

  public double getOutput_double_register_37() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_37(swigCPtr, this);
  }

  public void setOutput_double_register_37(double output_double_register_37) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_37(swigCPtr, this, output_double_register_37);
  }

  public double getOutput_double_register_38() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_38(swigCPtr, this);
  }

  public void setOutput_double_register_38(double output_double_register_38) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_38(swigCPtr, this, output_double_register_38);
  }

  public double getOutput_double_register_39() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_39(swigCPtr, this);
  }

  public void setOutput_double_register_39(double output_double_register_39) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_39(swigCPtr, this, output_double_register_39);
  }

  public double getOutput_double_register_40() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_40(swigCPtr, this);
  }

  public void setOutput_double_register_40(double output_double_register_40) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_40(swigCPtr, this, output_double_register_40);
  }

  public double getOutput_double_register_41() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_41(swigCPtr, this);
  }

  public void setOutput_double_register_41(double output_double_register_41) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_41(swigCPtr, this, output_double_register_41);
  }

  public double getOutput_double_register_42() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_42(swigCPtr, this);
  }

  public void setOutput_double_register_42(double output_double_register_42) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_42(swigCPtr, this, output_double_register_42);
  }

  public double getOutput_double_register_43() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_43(swigCPtr, this);
  }

  public void setOutput_double_register_43(double output_double_register_43) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_43(swigCPtr, this, output_double_register_43);
  }

  public double getOutput_double_register_44() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_44(swigCPtr, this);
  }

  public void setOutput_double_register_44(double output_double_register_44) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_44(swigCPtr, this, output_double_register_44);
  }

  public double getOutput_double_register_45() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_45(swigCPtr, this);
  }

  public void setOutput_double_register_45(double output_double_register_45) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_45(swigCPtr, this, output_double_register_45);
  }

  public double getOutput_double_register_46() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_46(swigCPtr, this);
  }

  public void setOutput_double_register_46(double output_double_register_46) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_46(swigCPtr, this, output_double_register_46);
  }

  public double getOutput_double_register_47() {
    return RTDE_MODULEJNI.RobotState_getOutput_double_register_47(swigCPtr, this);
  }

  public void setOutput_double_register_47(double output_double_register_47) {
    RTDE_MODULEJNI.RobotState_setOutput_double_register_47(swigCPtr, this, output_double_register_47);
  }

}
