/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.RTDE.impl;

public interface RTDE_MODULEConstants {
  public final static int MAJOR_VERSION = RTDE_MODULEJNI.MAJOR_VERSION_get();
  public final static int MINOR_VERSION = RTDE_MODULEJNI.MINOR_VERSION_get();
  public final static int CB3_MAJOR_VERSION = RTDE_MODULEJNI.CB3_MAJOR_VERSION_get();
  public final static int UR_CONTROLLER_RDY_FOR_CMD = RTDE_MODULEJNI.UR_CONTROLLER_RDY_FOR_CMD_get();
  public final static int UR_CONTROLLER_DONE_WITH_CMD = RTDE_MODULEJNI.UR_CONTROLLER_DONE_WITH_CMD_get();
  public final static int UR_EXECUTION_TIMEOUT = RTDE_MODULEJNI.UR_EXECUTION_TIMEOUT_get();
  public final static int UR_PATH_EXECUTION_TIMEOUT = RTDE_MODULEJNI.UR_PATH_EXECUTION_TIMEOUT_get();
  public final static int UR_GET_READY_TIMEOUT = RTDE_MODULEJNI.UR_GET_READY_TIMEOUT_get();
  public final static int RTDE_START_SYNCHRONIZATION_TIMEOUT = RTDE_MODULEJNI.RTDE_START_SYNCHRONIZATION_TIMEOUT_get();
  public final static double UR_JOINT_VELOCITY_MAX = RTDE_MODULEJNI.UR_JOINT_VELOCITY_MAX_get();
  public final static int UR_JOINT_VELOCITY_MIN = RTDE_MODULEJNI.UR_JOINT_VELOCITY_MIN_get();
  public final static double UR_JOINT_ACCELERATION_MAX = RTDE_MODULEJNI.UR_JOINT_ACCELERATION_MAX_get();
  public final static int UR_JOINT_ACCELERATION_MIN = RTDE_MODULEJNI.UR_JOINT_ACCELERATION_MIN_get();
  public final static double UR_TOOL_VELOCITY_MAX = RTDE_MODULEJNI.UR_TOOL_VELOCITY_MAX_get();
  public final static int UR_TOOL_VELOCITY_MIN = RTDE_MODULEJNI.UR_TOOL_VELOCITY_MIN_get();
  public final static double UR_TOOL_ACCELERATION_MAX = RTDE_MODULEJNI.UR_TOOL_ACCELERATION_MAX_get();
  public final static int UR_TOOL_ACCELERATION_MIN = RTDE_MODULEJNI.UR_TOOL_ACCELERATION_MIN_get();
  public final static double UR_SERVO_LOOKAHEAD_TIME_MAX = RTDE_MODULEJNI.UR_SERVO_LOOKAHEAD_TIME_MAX_get();
  public final static double UR_SERVO_LOOKAHEAD_TIME_MIN = RTDE_MODULEJNI.UR_SERVO_LOOKAHEAD_TIME_MIN_get();
  public final static int UR_SERVO_GAIN_MAX = RTDE_MODULEJNI.UR_SERVO_GAIN_MAX_get();
  public final static int UR_SERVO_GAIN_MIN = RTDE_MODULEJNI.UR_SERVO_GAIN_MIN_get();
  public final static double UR_BLEND_MAX = RTDE_MODULEJNI.UR_BLEND_MAX_get();
  public final static double UR_BLEND_MIN = RTDE_MODULEJNI.UR_BLEND_MIN_get();
}
