/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.RTDE.impl;

public class RTDE_MODULE implements RTDE_MODULEConstants {
  public static void set__doc_ur_rtde_RTDEControlInterface(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_RTDEControlInterface(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_RTDEControlInterface_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_RTDEControlInterface() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_RTDEControlInterface_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_RobotStatus(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_RobotStatus_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_RobotStatus() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_RobotStatus_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_RobotStatus_ROBOT_STATUS_POWER_BUTTON_PRESSED(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_RobotStatus_ROBOT_STATUS_POWER_BUTTON_PRESSED_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_RobotStatus_ROBOT_STATUS_POWER_BUTTON_PRESSED() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_RobotStatus_ROBOT_STATUS_POWER_BUTTON_PRESSED_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_RobotStatus_ROBOT_STATUS_POWER_ON(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_RobotStatus_ROBOT_STATUS_POWER_ON_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_RobotStatus_ROBOT_STATUS_POWER_ON() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_RobotStatus_ROBOT_STATUS_POWER_ON_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_RobotStatus_ROBOT_STATUS_PROGRAM_RUNNING(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_RobotStatus_ROBOT_STATUS_PROGRAM_RUNNING_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_RobotStatus_ROBOT_STATUS_PROGRAM_RUNNING() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_RobotStatus_ROBOT_STATUS_PROGRAM_RUNNING_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_RobotStatus_ROBOT_STATUS_TEACH_BUTTON_PRESSED(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_RobotStatus_ROBOT_STATUS_TEACH_BUTTON_PRESSED_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_RobotStatus_ROBOT_STATUS_TEACH_BUTTON_PRESSED() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_RobotStatus_ROBOT_STATUS_TEACH_BUTTON_PRESSED_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_db_client(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_db_client_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_db_client() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_db_client_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_endTeachMode(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_endTeachMode_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_endTeachMode() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_endTeachMode_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_forceModeSetDamping(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_forceModeSetDamping_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_forceModeSetDamping() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_forceModeSetDamping_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_forceModeSetGainScaling(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_forceModeSetGainScaling_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_forceModeSetGainScaling() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_forceModeSetGainScaling_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_forceModeStop(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_forceModeStop_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_forceModeStop() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_forceModeStop_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_getActualJointPositionsHistory(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_getActualJointPositionsHistory_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_getActualJointPositionsHistory() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_getActualJointPositionsHistory_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_getActualJointPositionsHistoryValue(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_getActualJointPositionsHistoryValue_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_getActualJointPositionsHistoryValue() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_getActualJointPositionsHistoryValue_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_getControlScriptState(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_getControlScriptState_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_getControlScriptState() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_getControlScriptState_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_getInverseKinematics(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_getInverseKinematics_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_getInverseKinematics() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_getInverseKinematics_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_poseTrans(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_poseTrans_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_poseTrans() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_poseTrans_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_getStepTime(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_getStepTime_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_getStepTime() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_getStepTime_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_getStepTimeValue(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_getStepTimeValue_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_getStepTimeValue() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_getStepTimeValue_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_getTargetWaypoint(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_getTargetWaypoint_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_getTargetWaypoint() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_getTargetWaypoint_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_getTargetWaypointValue(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_getTargetWaypointValue_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_getTargetWaypointValue() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_getTargetWaypointValue_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_getToolContactValue(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_getToolContactValue_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_getToolContactValue() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_getToolContactValue_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_hostname(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_hostname_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_hostname() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_hostname_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_isConnected(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_isConnected_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_isConnected() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_isConnected_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_isProgramRunning(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_isProgramRunning_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_isProgramRunning() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_isProgramRunning_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_moveC(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_moveC_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_moveC() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_moveC_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_moveJ_2(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_moveJ_2_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_moveJ_2() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_moveJ_2_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_moveJ_IK(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_moveJ_IK_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_moveJ_IK() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_moveJ_IK_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_moveL(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_moveL_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_moveL() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_moveL_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_moveL_2(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_moveL_2_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_moveL_2() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_moveL_2_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_moveL_FK(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_moveL_FK_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_moveL_FK() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_moveL_FK_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_moveP(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_moveP_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_moveP() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_moveP_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_port(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_port_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_port() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_port_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_prepareCmdScript(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_prepareCmdScript_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_prepareCmdScript() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_prepareCmdScript_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_receiveCallback(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_receiveCallback_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_receiveCallback() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_receiveCallback_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_reconnect(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_reconnect_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_reconnect() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_reconnect_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_reuploadScript(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_reuploadScript_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_reuploadScript() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_reuploadScript_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_robot_state(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_robot_state_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_robot_state() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_robot_state_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_rtde(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_rtde_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_rtde() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_rtde_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_script_client(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_script_client_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_script_client() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_script_client_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_sendClearCommand(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_sendClearCommand_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_sendClearCommand() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_sendClearCommand_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_sendCommand(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_sendCommand_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_sendCommand() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_sendCommand_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_sendCustomScriptFile(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_sendCustomScriptFile_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_sendCustomScriptFile() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_sendCustomScriptFile_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_sendCustomScriptFunction(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_sendCustomScriptFunction_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_sendCustomScriptFunction() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_sendCustomScriptFunction_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_servoC(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_servoC_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_servoC() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_servoC_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_servoJ(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_servoJ_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_servoJ() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_servoJ_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_servoL(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_servoL_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_servoL() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_servoL_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_servoStop(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_servoStop_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_servoStop() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_servoStop_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_setPayload(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_setPayload_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_setPayload() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_setPayload_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_setTcp(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_setTcp_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_setTcp() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_setTcp_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_setupRecipes(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_setupRecipes_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_setupRecipes() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_setupRecipes_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_speedJ(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_speedJ_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_speedJ() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_speedJ_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_stopScript(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_stopScript_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_stopScript() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_stopScript_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_stop_thread(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_stop_thread_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_stop_thread() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_stop_thread_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_teachMode(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_teachMode_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_teachMode() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_teachMode_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_th(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_th_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_th() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_th_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_toolContact(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_toolContact_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_toolContact() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_toolContact_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_triggerProtectiveStop(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_triggerProtectiveStop_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_triggerProtectiveStop() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_triggerProtectiveStop_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_verifyValueIsWithin(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_verifyValueIsWithin_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_verifyValueIsWithin() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_verifyValueIsWithin_get();
  }

  public static void set__doc_ur_rtde_RTDEControlInterface_zeroFtSensor(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_zeroFtSensor_set(value);
  }

  public static String get__doc_ur_rtde_RTDEControlInterface_zeroFtSensor() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEControlInterface_zeroFtSensor_get();
  }

  public static ProgramState parseProgramState(String state_str) {
    return ProgramState.swigToEnum(RTDE_MODULEJNI.parseProgramState(state_str));
  }

  public static String toString(ProgramState mode) {
    return RTDE_MODULEJNI.toString__SWIG_0(mode.swigValue());
  }

  public static SafetyMode parseSafetyMode(String state_str) {
    return SafetyMode.swigToEnum(RTDE_MODULEJNI.parseSafetyMode(state_str));
  }

  public static String toString(SafetyMode mode) {
    return RTDE_MODULEJNI.toString__SWIG_1(mode.swigValue());
  }

  public static SafetyStatus parseSafetyStatus(String state_str) {
    return SafetyStatus.swigToEnum(RTDE_MODULEJNI.parseSafetyStatus(state_str));
  }

  public static String toString(SafetyStatus mode) {
    return RTDE_MODULEJNI.toString__SWIG_2(mode.swigValue());
  }

  public static RobotMode parseRobotMode(String state_str) {
    return RobotMode.swigToEnum(RTDE_MODULEJNI.parseRobotMode(state_str));
  }

  public static String toString(RobotMode mode) {
    return RTDE_MODULEJNI.toString__SWIG_3(mode.swigValue());
  }

  public static String getNEW_LINE() {
    return RTDE_MODULEJNI.NEW_LINE_get();
  }

  public static String getQUOTATION() {
    return RTDE_MODULEJNI.QUOTATION_get();
  }

  public static void setUR_SCRIPT(String value) {
    RTDE_MODULEJNI.UR_SCRIPT_set(value);
  }

  public static String getUR_SCRIPT() {
    return RTDE_MODULEJNI.UR_SCRIPT_get();
  }

  public static void set__doc_ur_rtde_RTDEIOInterface(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_set(value);
  }

  public static String get__doc_ur_rtde_RTDEIOInterface() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_get();
  }

  public static void set__doc_ur_rtde_RTDEIOInterface_RTDEIOInterface(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_RTDEIOInterface_set(value);
  }

  public static String get__doc_ur_rtde_RTDEIOInterface_RTDEIOInterface() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_RTDEIOInterface_get();
  }

  public static void set__doc_ur_rtde_RTDEIOInterface_RobotStatus(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_RobotStatus_set(value);
  }

  public static String get__doc_ur_rtde_RTDEIOInterface_RobotStatus() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_RobotStatus_get();
  }

  public static void set__doc_ur_rtde_RTDEIOInterface_RobotStatus_ROBOT_STATUS_POWER_BUTTON_PRESSED(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_RobotStatus_ROBOT_STATUS_POWER_BUTTON_PRESSED_set(value);
  }

  public static String get__doc_ur_rtde_RTDEIOInterface_RobotStatus_ROBOT_STATUS_POWER_BUTTON_PRESSED() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_RobotStatus_ROBOT_STATUS_POWER_BUTTON_PRESSED_get();
  }

  public static void set__doc_ur_rtde_RTDEIOInterface_RobotStatus_ROBOT_STATUS_POWER_ON(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_RobotStatus_ROBOT_STATUS_POWER_ON_set(value);
  }

  public static String get__doc_ur_rtde_RTDEIOInterface_RobotStatus_ROBOT_STATUS_POWER_ON() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_RobotStatus_ROBOT_STATUS_POWER_ON_get();
  }

  public static void set__doc_ur_rtde_RTDEIOInterface_RobotStatus_ROBOT_STATUS_PROGRAM_RUNNING(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_RobotStatus_ROBOT_STATUS_PROGRAM_RUNNING_set(value);
  }

  public static String get__doc_ur_rtde_RTDEIOInterface_RobotStatus_ROBOT_STATUS_PROGRAM_RUNNING() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_RobotStatus_ROBOT_STATUS_PROGRAM_RUNNING_get();
  }

  public static void set__doc_ur_rtde_RTDEIOInterface_RobotStatus_ROBOT_STATUS_TEACH_BUTTON_PRESSED(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_RobotStatus_ROBOT_STATUS_TEACH_BUTTON_PRESSED_set(value);
  }

  public static String get__doc_ur_rtde_RTDEIOInterface_RobotStatus_ROBOT_STATUS_TEACH_BUTTON_PRESSED() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_RobotStatus_ROBOT_STATUS_TEACH_BUTTON_PRESSED_get();
  }

  public static void set__doc_ur_rtde_RTDEIOInterface_hostname(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_hostname_set(value);
  }

  public static String get__doc_ur_rtde_RTDEIOInterface_hostname() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_hostname_get();
  }

  public static void set__doc_ur_rtde_RTDEIOInterface_port(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_port_set(value);
  }

  public static String get__doc_ur_rtde_RTDEIOInterface_port() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_port_get();
  }

  public static void set__doc_ur_rtde_RTDEIOInterface_reconnect(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_reconnect_set(value);
  }

  public static String get__doc_ur_rtde_RTDEIOInterface_reconnect() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_reconnect_get();
  }

  public static void set__doc_ur_rtde_RTDEIOInterface_rtde(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_rtde_set(value);
  }

  public static String get__doc_ur_rtde_RTDEIOInterface_rtde() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_rtde_get();
  }

  public static void set__doc_ur_rtde_RTDEIOInterface_sendCommand(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_sendCommand_set(value);
  }

  public static String get__doc_ur_rtde_RTDEIOInterface_sendCommand() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_sendCommand_get();
  }

  public static void set__doc_ur_rtde_RTDEIOInterface_setAnalogOutputCurrent(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_setAnalogOutputCurrent_set(value);
  }

  public static String get__doc_ur_rtde_RTDEIOInterface_setAnalogOutputCurrent() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_setAnalogOutputCurrent_get();
  }

  public static void set__doc_ur_rtde_RTDEIOInterface_setAnalogOutputVoltage(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_setAnalogOutputVoltage_set(value);
  }

  public static String get__doc_ur_rtde_RTDEIOInterface_setAnalogOutputVoltage() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_setAnalogOutputVoltage_get();
  }

  public static void set__doc_ur_rtde_RTDEIOInterface_setSpeedSlider(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_setSpeedSlider_set(value);
  }

  public static String get__doc_ur_rtde_RTDEIOInterface_setSpeedSlider() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_setSpeedSlider_get();
  }

  public static void set__doc_ur_rtde_RTDEIOInterface_verifyValueIsWithin(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_verifyValueIsWithin_set(value);
  }

  public static String get__doc_ur_rtde_RTDEIOInterface_verifyValueIsWithin() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEIOInterface_verifyValueIsWithin_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_RTDEReceiveInterface(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_RTDEReceiveInterface_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_RTDEReceiveInterface() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_RTDEReceiveInterface_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getActualCurrent(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualCurrent_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getActualCurrent() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualCurrent_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getActualDigitalInputBits(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualDigitalInputBits_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getActualDigitalInputBits() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualDigitalInputBits_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getActualDigitalOutputBits(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualDigitalOutputBits_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getActualDigitalOutputBits() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualDigitalOutputBits_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getActualExecutionTime(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualExecutionTime_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getActualExecutionTime() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualExecutionTime_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getActualJointVoltage(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualJointVoltage_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getActualJointVoltage() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualJointVoltage_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getActualMainVoltage(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualMainVoltage_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getActualMainVoltage() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualMainVoltage_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getActualMomentum(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualMomentum_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getActualMomentum() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualMomentum_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getActualQ(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualQ_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getActualQ() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualQ_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getActualQd(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualQd_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getActualQd() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualQd_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getActualRobotCurrent(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualRobotCurrent_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getActualRobotCurrent() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualRobotCurrent_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getActualRobotVoltage(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualRobotVoltage_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getActualRobotVoltage() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualRobotVoltage_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getActualTCPPose(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualTCPPose_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getActualTCPPose() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualTCPPose_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getActualTCPSpeed(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualTCPSpeed_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getActualTCPSpeed() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualTCPSpeed_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getActualToolAccelerometer(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualToolAccelerometer_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getActualToolAccelerometer() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getActualToolAccelerometer_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getJointControlOutput(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getJointControlOutput_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getJointControlOutput() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getJointControlOutput_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getJointMode(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getJointMode_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getJointMode() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getJointMode_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getJointTemperatures(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getJointTemperatures_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getJointTemperatures() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getJointTemperatures_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getRobotMode(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getRobotMode_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getRobotMode() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getRobotMode_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getRobotStatus(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getRobotStatus_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getRobotStatus() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getRobotStatus_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getRuntimeState(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getRuntimeState_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getRuntimeState() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getRuntimeState_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getSafetyMode(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getSafetyMode_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getSafetyMode() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getSafetyMode_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getSpeedScaling(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getSpeedScaling_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getSpeedScaling() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getSpeedScaling_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getStandardAnalogInput0(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getStandardAnalogInput0_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getStandardAnalogInput0() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getStandardAnalogInput0_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getStandardAnalogInput1(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getStandardAnalogInput1_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getStandardAnalogInput1() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getStandardAnalogInput1_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getStandardAnalogOutput0(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getStandardAnalogOutput0_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getStandardAnalogOutput0() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getStandardAnalogOutput0_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getStandardAnalogOutput1(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getStandardAnalogOutput1_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getStandardAnalogOutput1() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getStandardAnalogOutput1_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getTargetCurrent(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getTargetCurrent_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getTargetCurrent() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getTargetCurrent_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getTargetMoment(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getTargetMoment_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getTargetMoment() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getTargetMoment_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getTargetQd(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getTargetQd_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getTargetQd() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getTargetQd_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getTargetQdd(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getTargetQdd_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getTargetQdd() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getTargetQdd_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getTargetSpeedFraction(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getTargetSpeedFraction_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getTargetSpeedFraction() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getTargetSpeedFraction_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getTargetTCPPose(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getTargetTCPPose_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getTargetTCPPose() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getTargetTCPPose_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getTargetTCPSpeed(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getTargetTCPSpeed_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getTargetTCPSpeed() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getTargetTCPSpeed_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_getTimestamp(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getTimestamp_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_getTimestamp() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_getTimestamp_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_hostname(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_hostname_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_hostname() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_hostname_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_isConnected(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_isConnected_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_isConnected() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_isConnected_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_port(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_port_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_port() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_port_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_receiveCallback(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_receiveCallback_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_receiveCallback() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_receiveCallback_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_reconnect(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_reconnect_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_reconnect() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_reconnect_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_robot_state(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_robot_state_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_robot_state() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_robot_state_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_rtde(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_rtde_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_rtde() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_rtde_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_setupRecipes(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_setupRecipes_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_setupRecipes() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_setupRecipes_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_stop_thread(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_stop_thread_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_stop_thread() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_stop_thread_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_th(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_th_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_th() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_th_get();
  }

  public static void set__doc_ur_rtde_RTDEReceiveInterface_variables(String value) {
    RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_variables_set(value);
  }

  public static String get__doc_ur_rtde_RTDEReceiveInterface_variables() {
    return RTDE_MODULEJNI.__doc_ur_rtde_RTDEReceiveInterface_variables_get();
  }

}
