/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.RTDE.impl;

public class RTDEIOInterface {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RTDEIOInterface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RTDEIOInterface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RTDE_MODULEJNI.delete_RTDEIOInterface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RTDEIOInterface(String hostname, int port, boolean verbose) {
    this(RTDE_MODULEJNI.new_RTDEIOInterface__SWIG_0(hostname, port, verbose), true);
  }

  public RTDEIOInterface(String hostname, int port) {
    this(RTDE_MODULEJNI.new_RTDEIOInterface__SWIG_1(hostname, port), true);
  }

  public RTDEIOInterface(String hostname) {
    this(RTDE_MODULEJNI.new_RTDEIOInterface__SWIG_2(hostname), true);
  }

  public boolean reconnect() {
    return RTDE_MODULEJNI.RTDEIOInterface_reconnect(swigCPtr, this);
  }

  public boolean setStandardDigitalOut(short output_id, boolean signal_level) {
    return RTDE_MODULEJNI.RTDEIOInterface_setStandardDigitalOut(swigCPtr, this, output_id, signal_level);
  }

  public boolean setToolDigitalOut(short output_id, boolean signal_level) {
    return RTDE_MODULEJNI.RTDEIOInterface_setToolDigitalOut(swigCPtr, this, output_id, signal_level);
  }

  public boolean setSpeedSlider(double speed) {
    return RTDE_MODULEJNI.RTDEIOInterface_setSpeedSlider(swigCPtr, this, speed);
  }

  public boolean setAnalogOutputVoltage(short output_id, double voltage_ratio) {
    return RTDE_MODULEJNI.RTDEIOInterface_setAnalogOutputVoltage(swigCPtr, this, output_id, voltage_ratio);
  }

  public boolean setAnalogOutputCurrent(short output_id, double current_ratio) {
    return RTDE_MODULEJNI.RTDEIOInterface_setAnalogOutputCurrent(swigCPtr, this, output_id, current_ratio);
  }

  public final static class RobotStatus {
    public final static RTDEIOInterface.RobotStatus ROBOT_STATUS_POWER_ON = new RTDEIOInterface.RobotStatus("ROBOT_STATUS_POWER_ON", RTDE_MODULEJNI.RTDEIOInterface_ROBOT_STATUS_POWER_ON_get());
    public final static RTDEIOInterface.RobotStatus ROBOT_STATUS_PROGRAM_RUNNING = new RTDEIOInterface.RobotStatus("ROBOT_STATUS_PROGRAM_RUNNING", RTDE_MODULEJNI.RTDEIOInterface_ROBOT_STATUS_PROGRAM_RUNNING_get());
    public final static RTDEIOInterface.RobotStatus ROBOT_STATUS_TEACH_BUTTON_PRESSED = new RTDEIOInterface.RobotStatus("ROBOT_STATUS_TEACH_BUTTON_PRESSED", RTDE_MODULEJNI.RTDEIOInterface_ROBOT_STATUS_TEACH_BUTTON_PRESSED_get());
    public final static RTDEIOInterface.RobotStatus ROBOT_STATUS_POWER_BUTTON_PRESSED = new RTDEIOInterface.RobotStatus("ROBOT_STATUS_POWER_BUTTON_PRESSED", RTDE_MODULEJNI.RTDEIOInterface_ROBOT_STATUS_POWER_BUTTON_PRESSED_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static RobotStatus swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + RobotStatus.class + " with value " + swigValue);
    }

    private RobotStatus(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private RobotStatus(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private RobotStatus(String swigName, RobotStatus swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static RobotStatus[] swigValues = { ROBOT_STATUS_POWER_ON, ROBOT_STATUS_PROGRAM_RUNNING, ROBOT_STATUS_TEACH_BUTTON_PRESSED, ROBOT_STATUS_POWER_BUTTON_PRESSED };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
