/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.RTDE.impl;

public class RTDEUtility {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RTDEUtility(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RTDEUtility obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RTDE_MODULEJNI.delete_RTDEUtility(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static VectorChar packUInt32(long uint32) {
    return new VectorChar(RTDE_MODULEJNI.RTDEUtility_packUInt32(uint32), true);
  }

  public static VectorChar packInt32(int int32) {
    return new VectorChar(RTDE_MODULEJNI.RTDEUtility_packInt32(int32), true);
  }

  public static VectorChar packVectorNInt32(VectorInt vector_n_int32) {
    return new VectorChar(RTDE_MODULEJNI.RTDEUtility_packVectorNInt32(VectorInt.getCPtr(vector_n_int32), vector_n_int32), true);
  }

  public static VectorChar packVectorNd(VectorDouble vector_nd) {
    return new VectorChar(RTDE_MODULEJNI.RTDEUtility_packVectorNd(VectorDouble.getCPtr(vector_nd), vector_nd), true);
  }

  public static VectorChar packDouble(double d) {
    return new VectorChar(RTDE_MODULEJNI.RTDEUtility_packDouble(d), true);
  }

  public static VectorDouble unpackVector3d(VectorChar data, SWIGTYPE_p_unsigned_int message_offset) {
    return new VectorDouble(RTDE_MODULEJNI.RTDEUtility_unpackVector3d(VectorChar.getCPtr(data), data, SWIGTYPE_p_unsigned_int.getCPtr(message_offset)), true);
  }

  public static VectorDouble unpackVector6d(VectorChar data, SWIGTYPE_p_unsigned_int message_offset) {
    return new VectorDouble(RTDE_MODULEJNI.RTDEUtility_unpackVector6d(VectorChar.getCPtr(data), data, SWIGTYPE_p_unsigned_int.getCPtr(message_offset)), true);
  }

  public static VectorInt unpackVector6Int32(VectorChar data, SWIGTYPE_p_unsigned_int message_offset) {
    return new VectorInt(RTDE_MODULEJNI.RTDEUtility_unpackVector6Int32(VectorChar.getCPtr(data), data, SWIGTYPE_p_unsigned_int.getCPtr(message_offset)), true);
  }

  public static double getDouble(VectorChar data, SWIGTYPE_p_unsigned_int message_offset) {
    return RTDE_MODULEJNI.RTDEUtility_getDouble(VectorChar.getCPtr(data), data, SWIGTYPE_p_unsigned_int.getCPtr(message_offset));
  }

  public static long getUInt32(VectorChar data, SWIGTYPE_p_unsigned_int message_offset) {
    return RTDE_MODULEJNI.RTDEUtility_getUInt32(VectorChar.getCPtr(data), data, SWIGTYPE_p_unsigned_int.getCPtr(message_offset));
  }

  public static int getUInt16(VectorChar data, SWIGTYPE_p_unsigned_int message_offset) {
    return RTDE_MODULEJNI.RTDEUtility_getUInt16(VectorChar.getCPtr(data), data, SWIGTYPE_p_unsigned_int.getCPtr(message_offset));
  }

  public static int getInt32(VectorChar data, SWIGTYPE_p_unsigned_int message_offset) {
    return RTDE_MODULEJNI.RTDEUtility_getInt32(VectorChar.getCPtr(data), data, SWIGTYPE_p_unsigned_int.getCPtr(message_offset));
  }

  public static java.math.BigInteger getUInt64(VectorChar data, SWIGTYPE_p_unsigned_int message_offset) {
    return RTDE_MODULEJNI.RTDEUtility_getUInt64(VectorChar.getCPtr(data), data, SWIGTYPE_p_unsigned_int.getCPtr(message_offset));
  }

  public static short getUChar(VectorChar data, SWIGTYPE_p_unsigned_int message_offset) {
    return RTDE_MODULEJNI.RTDEUtility_getUChar(VectorChar.getCPtr(data), data, SWIGTYPE_p_unsigned_int.getCPtr(message_offset));
  }

  public static String double2hexstr(double x) {
    return RTDE_MODULEJNI.RTDEUtility_double2hexstr(x);
  }

  public static VectorChar hexToBytes(String hex) {
    return new VectorChar(RTDE_MODULEJNI.RTDEUtility_hexToBytes(hex), true);
  }

  public static SWIGTYPE_p_std__ostream hexDump(SWIGTYPE_p_std__ostream o, String p, long size) {
    return new SWIGTYPE_p_std__ostream(RTDE_MODULEJNI.RTDEUtility_hexDump(SWIGTYPE_p_std__ostream.getCPtr(o), p, size), false);
  }

  public static VectorString split(String s, char delimiter) {
    return new VectorString(RTDE_MODULEJNI.RTDEUtility_split(s, delimiter), true);
  }

  public RTDEUtility() {
    this(RTDE_MODULEJNI.new_RTDEUtility(), true);
  }

}
