/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.RTDE.impl;

public final class SafetyStatus {
  public final static SafetyStatus NORMAL = new SafetyStatus("NORMAL");
  public final static SafetyStatus REDUCED = new SafetyStatus("REDUCED");
  public final static SafetyStatus PROTECTIVE_STOP = new SafetyStatus("PROTECTIVE_STOP");
  public final static SafetyStatus RECOVERY = new SafetyStatus("RECOVERY");
  public final static SafetyStatus SAFEGUARD_STOP = new SafetyStatus("SAFEGUARD_STOP");
  public final static SafetyStatus SYSTEM_EMERGENCY_STOP = new SafetyStatus("SYSTEM_EMERGENCY_STOP");
  public final static SafetyStatus ROBOT_EMERGENCY_STOP = new SafetyStatus("ROBOT_EMERGENCY_STOP");
  public final static SafetyStatus VIOLATION = new SafetyStatus("VIOLATION");
  public final static SafetyStatus FAULT = new SafetyStatus("FAULT");
  public final static SafetyStatus AUTOMATIC_MODE_SAFEGUARD_STOP = new SafetyStatus("AUTOMATIC_MODE_SAFEGUARD_STOP");
  public final static SafetyStatus SYSTEM_THREE_POSITION_ENABLING_STOP = new SafetyStatus("SYSTEM_THREE_POSITION_ENABLING_STOP");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SafetyStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SafetyStatus.class + " with value " + swigValue);
  }

  private SafetyStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SafetyStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SafetyStatus(String swigName, SafetyStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SafetyStatus[] swigValues = { NORMAL, REDUCED, PROTECTIVE_STOP, RECOVERY, SAFEGUARD_STOP, SYSTEM_EMERGENCY_STOP, ROBOT_EMERGENCY_STOP, VIOLATION, FAULT, AUTOMATIC_MODE_SAFEGUARD_STOP, SYSTEM_THREE_POSITION_ENABLING_STOP };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

