/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.RTDE.impl;

public final class SafetyMode {
  public final static SafetyMode NORMAL = new SafetyMode("NORMAL");
  public final static SafetyMode REDUCED = new SafetyMode("REDUCED");
  public final static SafetyMode PROTECTIVE_STOP = new SafetyMode("PROTECTIVE_STOP");
  public final static SafetyMode RECOVERY = new SafetyMode("RECOVERY");
  public final static SafetyMode SAFEGUARD_STOP = new SafetyMode("SAFEGUARD_STOP");
  public final static SafetyMode SYSTEM_EMERGENCY_STOP = new SafetyMode("SYSTEM_EMERGENCY_STOP");
  public final static SafetyMode ROBOT_EMERGENCY_STOP = new SafetyMode("ROBOT_EMERGENCY_STOP");
  public final static SafetyMode VIOLATION = new SafetyMode("VIOLATION");
  public final static SafetyMode FAULT = new SafetyMode("FAULT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SafetyMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SafetyMode.class + " with value " + swigValue);
  }

  private SafetyMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SafetyMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SafetyMode(String swigName, SafetyMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SafetyMode[] swigValues = { NORMAL, REDUCED, PROTECTIVE_STOP, RECOVERY, SAFEGUARD_STOP, SYSTEM_EMERGENCY_STOP, ROBOT_EMERGENCY_STOP, VIOLATION, FAULT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

