/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.RTDE.impl;

public class ScriptClient {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ScriptClient(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ScriptClient obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RTDE_MODULEJNI.delete_ScriptClient(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ScriptClient(String hostname, long major_control_version, long minor_control_version, int port, boolean verbose) {
    this(RTDE_MODULEJNI.new_ScriptClient__SWIG_0(hostname, major_control_version, minor_control_version, port, verbose), true);
  }

  public ScriptClient(String hostname, long major_control_version, long minor_control_version, int port) {
    this(RTDE_MODULEJNI.new_ScriptClient__SWIG_1(hostname, major_control_version, minor_control_version, port), true);
  }

  public ScriptClient(String hostname, long major_control_version, long minor_control_version) {
    this(RTDE_MODULEJNI.new_ScriptClient__SWIG_2(hostname, major_control_version, minor_control_version), true);
  }

  public void connect() {
    RTDE_MODULEJNI.ScriptClient_connect(swigCPtr, this);
  }

  public void disconnect() {
    RTDE_MODULEJNI.ScriptClient_disconnect(swigCPtr, this);
  }

  public boolean isConnected() {
    return RTDE_MODULEJNI.ScriptClient_isConnected(swigCPtr, this);
  }

  public boolean sendScript() {
    return RTDE_MODULEJNI.ScriptClient_sendScript__SWIG_0(swigCPtr, this);
  }

  public boolean sendScript(String file_name) {
    return RTDE_MODULEJNI.ScriptClient_sendScript__SWIG_1(swigCPtr, this, file_name);
  }

  public boolean sendScriptCommand(String cmd_str) {
    return RTDE_MODULEJNI.ScriptClient_sendScriptCommand(swigCPtr, this, cmd_str);
  }

  public final static class ConnectionState {
    public final static ScriptClient.ConnectionState DISCONNECTED = new ScriptClient.ConnectionState("DISCONNECTED", RTDE_MODULEJNI.ScriptClient_ConnectionState_DISCONNECTED_get());
    public final static ScriptClient.ConnectionState CONNECTED = new ScriptClient.ConnectionState("CONNECTED", RTDE_MODULEJNI.ScriptClient_ConnectionState_CONNECTED_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static ConnectionState swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + ConnectionState.class + " with value " + swigValue);
    }

    private ConnectionState(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private ConnectionState(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private ConnectionState(String swigName, ConnectionState swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static ConnectionState[] swigValues = { DISCONNECTED, CONNECTED };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
