/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.RTDE.impl;

public final class UserRole {
  public final static UserRole PROGRAMMER = new UserRole("PROGRAMMER");
  public final static UserRole OPERATOR = new UserRole("OPERATOR");
  public final static UserRole NONE = new UserRole("NONE");
  public final static UserRole LOCKED = new UserRole("LOCKED");
  public final static UserRole RESTRICTED = new UserRole("RESTRICTED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static UserRole swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + UserRole.class + " with value " + swigValue);
  }

  private UserRole(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private UserRole(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private UserRole(String swigName, UserRole swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static UserRole[] swigValues = { PROGRAMMER, OPERATOR, NONE, LOCKED, RESTRICTED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

