/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.RTDE.impl;

public class VectorChar extends java.util.AbstractList<Character> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorChar(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorChar obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RTDE_MODULEJNI.delete_VectorChar(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorChar(char[] initialElements) {
    this();
    reserve(initialElements.length);

    for (char element : initialElements) {
      add(element);
    }
  }

  public VectorChar(Iterable<Character> initialElements) {
    this();
    for (char element : initialElements) {
      add(element);
    }
  }

  public Character get(int index) {
    return doGet(index);
  }

  public Character set(int index, Character e) {
    return doSet(index, e);
  }

  public boolean add(Character e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Character e) {
    modCount++;
    doAdd(index, e);
  }

  public Character remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public VectorChar() {
    this(RTDE_MODULEJNI.new_VectorChar__SWIG_0(), true);
  }

  public VectorChar(VectorChar other) {
    this(RTDE_MODULEJNI.new_VectorChar__SWIG_1(VectorChar.getCPtr(other), other), true);
  }

  public long capacity() {
    return RTDE_MODULEJNI.VectorChar_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    RTDE_MODULEJNI.VectorChar_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return RTDE_MODULEJNI.VectorChar_isEmpty(swigCPtr, this);
  }

  public void clear() {
    RTDE_MODULEJNI.VectorChar_clear(swigCPtr, this);
  }

  public VectorChar(int count, char value) {
    this(RTDE_MODULEJNI.new_VectorChar__SWIG_2(count, value), true);
  }

  private int doSize() {
    return RTDE_MODULEJNI.VectorChar_doSize(swigCPtr, this);
  }

  private void doAdd(char x) {
    RTDE_MODULEJNI.VectorChar_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, char x) {
    RTDE_MODULEJNI.VectorChar_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private char doRemove(int index) {
    return RTDE_MODULEJNI.VectorChar_doRemove(swigCPtr, this, index);
  }

  private char doGet(int index) {
    return RTDE_MODULEJNI.VectorChar_doGet(swigCPtr, this, index);
  }

  private char doSet(int index, char val) {
    return RTDE_MODULEJNI.VectorChar_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    RTDE_MODULEJNI.VectorChar_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
