/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.dhbw.rahmlab.RTDE.impl;

public class ViconDataStreamSDKSwigJNI {
  public final static native long new_VectorUint__SWIG_0();
  public final static native long new_VectorUint__SWIG_1(long jarg1, VectorUint jarg1_);
  public final static native long VectorUint_capacity(long jarg1, VectorUint jarg1_);
  public final static native void VectorUint_reserve(long jarg1, VectorUint jarg1_, long jarg2);
  public final static native boolean VectorUint_isEmpty(long jarg1, VectorUint jarg1_);
  public final static native void VectorUint_clear(long jarg1, VectorUint jarg1_);
  public final static native long new_VectorUint__SWIG_2(int jarg1, long jarg2);
  public final static native int VectorUint_doSize(long jarg1, VectorUint jarg1_);
  public final static native void VectorUint_doAdd__SWIG_0(long jarg1, VectorUint jarg1_, long jarg2);
  public final static native void VectorUint_doAdd__SWIG_1(long jarg1, VectorUint jarg1_, int jarg2, long jarg3);
  public final static native long VectorUint_doRemove(long jarg1, VectorUint jarg1_, int jarg2);
  public final static native long VectorUint_doGet(long jarg1, VectorUint jarg1_, int jarg2);
  public final static native long VectorUint_doSet(long jarg1, VectorUint jarg1_, int jarg2, long jarg3);
  public final static native void VectorUint_doRemoveRange(long jarg1, VectorUint jarg1_, int jarg2, int jarg3);
  public final static native void delete_VectorUint(long jarg1);
  public final static native long new_VectorVectorUchar__SWIG_0();
  public final static native long new_VectorVectorUchar__SWIG_1(long jarg1, VectorVectorUchar jarg1_);
  public final static native long VectorVectorUchar_capacity(long jarg1, VectorVectorUchar jarg1_);
  public final static native void VectorVectorUchar_reserve(long jarg1, VectorVectorUchar jarg1_, long jarg2);
  public final static native boolean VectorVectorUchar_isEmpty(long jarg1, VectorVectorUchar jarg1_);
  public final static native void VectorVectorUchar_clear(long jarg1, VectorVectorUchar jarg1_);
  public final static native long new_VectorVectorUchar__SWIG_2(int jarg1, long jarg2, VectorUchar jarg2_);
  public final static native int VectorVectorUchar_doSize(long jarg1, VectorVectorUchar jarg1_);
  public final static native void VectorVectorUchar_doAdd__SWIG_0(long jarg1, VectorVectorUchar jarg1_, long jarg2, VectorUchar jarg2_);
  public final static native void VectorVectorUchar_doAdd__SWIG_1(long jarg1, VectorVectorUchar jarg1_, int jarg2, long jarg3, VectorUchar jarg3_);
  public final static native long VectorVectorUchar_doRemove(long jarg1, VectorVectorUchar jarg1_, int jarg2);
  public final static native long VectorVectorUchar_doGet(long jarg1, VectorVectorUchar jarg1_, int jarg2);
  public final static native long VectorVectorUchar_doSet(long jarg1, VectorVectorUchar jarg1_, int jarg2, long jarg3, VectorUchar jarg3_);
  public final static native void VectorVectorUchar_doRemoveRange(long jarg1, VectorVectorUchar jarg1_, int jarg2, int jarg3);
  public final static native void delete_VectorVectorUchar(long jarg1);
  public final static native long new_VectorUchar__SWIG_0();
  public final static native long new_VectorUchar__SWIG_1(long jarg1, VectorUchar jarg1_);
  public final static native long VectorUchar_capacity(long jarg1, VectorUchar jarg1_);
  public final static native void VectorUchar_reserve(long jarg1, VectorUchar jarg1_, long jarg2);
  public final static native boolean VectorUchar_isEmpty(long jarg1, VectorUchar jarg1_);
  public final static native void VectorUchar_clear(long jarg1, VectorUchar jarg1_);
  public final static native long new_VectorUchar__SWIG_2(int jarg1, short jarg2);
  public final static native int VectorUchar_doSize(long jarg1, VectorUchar jarg1_);
  public final static native void VectorUchar_doAdd__SWIG_0(long jarg1, VectorUchar jarg1_, short jarg2);
  public final static native void VectorUchar_doAdd__SWIG_1(long jarg1, VectorUchar jarg1_, int jarg2, short jarg3);
  public final static native short VectorUchar_doRemove(long jarg1, VectorUchar jarg1_, int jarg2);
  public final static native short VectorUchar_doGet(long jarg1, VectorUchar jarg1_, int jarg2);
  public final static native short VectorUchar_doSet(long jarg1, VectorUchar jarg1_, int jarg2, short jarg3);
  public final static native void VectorUchar_doRemoveRange(long jarg1, VectorUchar jarg1_, int jarg2, int jarg3);
  public final static native void delete_VectorUchar(long jarg1);
  public final static native long new_SharedPtrVectorUchar();
  public final static native void delete_SharedPtrVectorUchar(long jarg1);
}
